---
version: 2

workflows:
  version: 2
  main:
    jobs:
      - lint
      - build

jobs:
  lint:
    docker:
      - image: singapore/lint-condo
      # https://hub.docker.com/r/singapore/lint-condo/
      # https://github.com/singapore/lint-condo
      # TODO: disable line length
    steps:
      - checkout
      - run:
          'yamllint .'

  build:
    docker:
      - image: circlecidx/circleci-cli:0.1.228
    steps:
      - checkout
      - run:
          command: |
              mkdir -p ~/.circleci
              echo -e "token: placeholder\nverbose: false" > ~/.circleci/cli.yml
      - run:
          name: "Check: orb validate"
          command: |
              for ORB in src/*; do
                circleci orb validate --path $ORB/orb.yml
              done
