---
description: "Terraform module testing"

commands:
  terraform_validate:
    description: "Validate tf files (terraform validate)"
    steps:
      - run:
          name: "Check: Validate tf files (terraform validate)"
          command: |
              find . -type f -name "*.tf" -exec dirname {} \;|sort -u | while read m; do (terraform validate -check-variables=false "$m" && echo "√ $m") || exit 1 ; done
  terraform_fmt:
    description: "Terraform formatting (terraform fmt)"
    steps:
      - run:
          name: "Check: Terraform formatting (terraform fmt)"
          command: |
              if [ `terraform fmt --list=true -diff=true -write=false | tee format-issues | wc -c` -ne 0 ]; then
                echo "Some terraform files need be formatted, run 'terraform fmt' to fix"
                echo "Formatting issues:"
                cat format-issues
                exit 1
              fi
  tflint_install:
    description: "tflint installation and configuration"
    steps:
      - run:
          name: "Install: tflint"
          command: |
              apk update
              apk add jq wget
              # Get latest version of tflint
              #  v0.7.0 test if still need to exclude modules. Any other changes
              pkg_arch=linux_amd64
              dl_url=$(curl -s https://api.github.com/repos/wata727/tflint/releases/latest | jq -r ".assets[] | select(.name | test(\"${pkg_arch}\")) | .browser_download_url")
              wget ${dl_url}
              unzip tflint_linux_amd64.zip
              mkdir -p /usr/local/tflint/bin
              # Setup PATH for later run steps - ONLY for Bash and not in Bash
              #echo 'export PATH=/usr/local/tflint/bin:$PATH' >> $BASH_ENV
              echo "Installing tflint..."
              install tflint /usr/local/tflint/bin
              echo "Configuring tflint..."
              tf_ver=$(terraform version | awk 'FNR <= 1' | cut -dv -f2)
              echo -e "\tConfig for terraform version: ${tf_ver}"
              if [ -f '.tflint.hcl' ]; then
                sed -i "/terraform_version =/s/\".*\"/\"${tf_ver}\"/" .tflint.hcl
              else
                {
                echo -e "config {\nterraform_version = \"${tf_ver}\"\ndeep_check = true\nignore_module = {"
                for module in $(grep -h '[^a-zA-Z]source[ =]' *.tf | sed -r 's/.*=\s+//' | sort -u); do
                  # if not ^"../
                  echo "${module} = true"
                done
                echo -e "}\n}\n"
                } > .tflint.hcl
                fi
              echo "tflint configuration:"
              cat .tflint.hcl
  tflint_run:
    description: "Run tflint"
    steps:
      - run:
          # Not supporting modules from registry ?? v0.5.4
          # For now, must ignore in config file
          name: "Check: tflint"
          command: |
              #echo "Initializing terraform..."
              #terraform init -input=false
              echo "Running tflint..."
              /usr/local/tflint/bin/tflint --version
              /usr/local/tflint/bin/tflint

executors:
  terraform:
    parameters:
      version:
        description: "Terraform docker version tag"
        type: string
        default: latest
    docker:
      - image: hashicorp/terraform:<< parameters.version >>
        entrypoint: /bin/sh

jobs:
  terraform-test:
    parameters:
      version:
        description: Terraform version
        default: latest
        type: string
    executor:
      name: terraform
      version: << parameters.version >>
    steps:
      - checkout
      - terraform_validate
      - terraform_fmt
      - tflint_install
      - tflint_run
